import { test, expect } from '@playwright/test';

test('register, profile, password, help and logout', async ({ page }, info) => {
  const email = `browser-${Date.now()}-${info.project.name}@example.test`;
  await page.goto('/perfil');
  await expect(page.getByRole('heading', { name: 'Iniciar sesion' })).toBeVisible();
  await page.getByRole('button', { name: 'Crear cuenta', exact: true }).click();
  await page.getByLabel('Nombre completo', { exact: true }).fill('Usuario de prueba');
  await page.getByLabel('Correo electronico', { exact: true }).fill(email);
  await page.getByLabel('Contrasena', { exact: true }).fill('Testing123!');
  await page.getByLabel('Confirmar contrasena', { exact: true }).fill('Testing123!');
  await page.getByRole('button', { name: 'Crear cuenta', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Perfil de usuario' })).toBeVisible();
  await expect(page.getByText('Vendedor', { exact: true }).first()).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Usuario de prueba' })).toBeVisible();
  await page.getByRole('button', { name: 'Abrir guia de ayuda' }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await expect(page.getByText('PASO 2 DE 4')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button', { name: 'Cambiar contrasena' }).click();
  await page.getByLabel('Contrasena actual', { exact: true }).fill('Testing123!');
  await page.getByLabel('Nueva contrasena', { exact: true }).fill('Updated456!');
  await page.getByLabel('Confirmar nueva contrasena', { exact: true }).fill('Updated456!');
  await page.getByRole('button', { name: 'Guardar contrasena' }).click();
  await expect(page.getByRole('status')).toHaveText('Tu contrasena se actualizo correctamente.');
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Usuario de prueba' })).toBeVisible();
  await page.screenshot({ path: `test-results/profile-${info.project.name}.png`, fullPage: true });
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  expect(overflow).toBe(false);
  await page.getByRole('button', { name: 'Cerrar sesion' }).click();
  await expect(page.getByRole('heading', { name: 'Iniciar sesion' })).toBeVisible();
  await page.getByLabel('Correo electronico').fill(email);
  await page.getByLabel('Contrasena', { exact: true }).fill('Testing123!');
  await page.getByRole('button', { name: 'Ingresar' }).click();
  await expect(page.getByRole('alert')).toBeVisible();
  await page.getByLabel('Contrasena', { exact: true }).fill('Updated456!');
  await page.getByRole('button', { name: 'Ingresar' }).click();
  await expect(page.getByRole('heading', { name: 'Perfil de usuario' })).toBeVisible();
});
