import { test, expect } from '@playwright/test';
test('settings persist, apply to profile and show contextual help', async ({ page }, info) => {
  await page.goto('/login');
  await page.getByRole('button', { name: 'Crear cuenta', exact: true }).click();
  await page.getByLabel('Nombre completo', { exact: true }).fill('Prueba ajustes');
  await page.getByLabel('Correo electronico').fill(`settings-${Date.now()}@example.test`);
  await page.getByLabel('Contrasena', { exact: true }).fill('Testing123!');
  await page.getByLabel('Confirmar contrasena', { exact: true }).fill('Testing123!');
  await page.getByRole('button', { name: 'Crear cuenta', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Prueba ajustes' })).toBeVisible();
  await page.getByRole('link', { name: 'Ajustes', exact: true }).click();
  await page.getByRole('radio', { name: 'Oscuro', exact: true }).check();
  await page.getByRole('radio', { name: 'Compacta' }).check();
  await page.getByRole('button', { name: 'Guardar ajustes' }).click();
  await expect(page.getByRole('status')).toHaveText('Tus ajustes se guardaron correctamente.');
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.reload();
  await expect(page.getByRole('radio', { name: 'Oscuro', exact: true })).toBeChecked();
  await expect(page.getByRole('radio', { name: 'Compacta' })).toBeChecked();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await expect(page.locator('html')).toHaveAttribute('data-density', 'compact');
  await page.screenshot({ path: `test-results/settings-${info.project.name}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  await page.getByRole('button', { name: 'Abrir guia de ayuda' }).click();
  await expect(page.getByRole('heading', { name: 'Ayuda: Ajustes' })).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Restablecer valores' }).click();
  await page.getByRole('button', { name: 'Guardar ajustes' }).click();
  await expect(page.getByRole('status')).toHaveText('Tus ajustes se guardaron correctamente.');
  await page.getByRole('link', { name: 'Contrasena y perfil' }).click();
  await expect(page.getByRole('heading', { name: 'Prueba ajustes' })).toBeVisible();
});
